# This workflow opens and updates a pull request with a new package version
# based on code changes.

# The pull request updates the version in composer.json, updates the changelog
# and creates release tags.

# For more information, see https://github.com/marketplace/actions/release-please-action


on:
  push:
    branches:
      - master
  
permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7.10
        with:
          release-type: php
          package-name: release-please-action
          pull-request-title-pattern: "chore(release): ${version}"
          pull-request-header: ":robot: Merge this PR to release a new version"

  publish-package:
    needs: release-please
    if: contains(github.event.head_commit.message, 'chore(release)') 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Release Package
        uses: hotaruma/packagist-sync@v1.0.1
        with:
          packagist-username: ${{ secrets.PACKAGIST_USERNAME }}
          api-token: ${{ secrets.PACKAGIST_TOKEN }}
          